### ISSUE TITLE
Memory distribution when evaluate model with 2gpu per process

### ISSUE THREAD

**Issue by hulianyuyy** [EvolvingLMMs-Lab/lmms-eval#191]
I have referred to the issues raised by previous researchers and try to evaluate the model with 2 gpus by setting `device_map=auto`. But i notice that only the model is loaded across several gpus, but the consumed memory during the model forward process is only distributed in the last gpu, which still cause OOM error. My command is as follows. Do you have any suggestion?
`CUDA_VISIBLE_DEVICES=0,1 lmms-eval --model llava_onevision --model_args pretrained=xxx,conv_template=qwen_1_5,model_name=llava_qwen,device_map=auto --tasks mvbench --batch_size 1 --log_samples --log_samples_suffix llava_onevision --output_path ./logs/`
I also try using accelerate launch, but get similar results.
`CUDA_VISIBLE_DEVICES=0,1 accelerate launch --num_processes=1 -m lmms_eval --model llava_onevision --model_args pretrained=xxx,conv_template=qwen_1_5,model_name=llava_qwen,device_map=auto --tasks mvbench --batch_size 1 --log_samples --log_samples_suffix llava_onevision --output_path ./logs/`

**Comment by hulianyuyy** [comment]
Besides, when i try to evaluate `llava-onevision-qwen2-0.5b-ov` on a 3090 GPU with 24GB memory, i also encounter OOM error. But this should not happen as it should only consume 4GB as depicted in the readme.md. This is the command i conduct
`CUDA_VISIBLE_DEVICES=0 accelerate launch --num_processes=1 -m lmms_eval --model llava_onevision --model_args pretrained=path_to/llava-onevision-qwen2-0.5b-ov,conv_template=qwen_1_5,model_name=llava_qwen --tasks mvbench --batch_size 1 --log_samples --log_samples_suffix llava_onevision --output_path ./logs/`

**Comment by kcz358** [comment]
This is because the `device_map=auto` is simply put different layers of the model at different gpus. It will perform forward pass one gpu at a time and pass the hidden states to the next gpu. Thus you will see that the usage of the gpu will increase one by one during inference. You can try to use the `srt_model` and set up a sglang server for a true tensor parallel evaluation if you are still encountering OOM or you can simply reduce the number of frames loaded for llava in `model_args`

**Comment by mikeallen39** [comment]
> Thanks for your response.



Hi, I seem to have encountered the same problem, have you solved it?

**Comment by hulianyuyy** [comment]
`lmms-eval --model llava_onevision --model_args pretrained=/path_to_your_checkpoint,conv_template=qwen_1_5,model_name=llava_qwen_training_free,device_map=auto --task your_benchmark  --batch_size 1 --log_samples --log_samples_suffix llava_onevision_7b --output_path ./log` can successfully run.

**Comment by mikeallen39** [comment]
> `lmms-eval --model llava_onevision --model_args pretrained=/path_to_your_checkpoint,conv_template=qwen_1_5,model_name=llava_qwen_training_free,device_map=auto --task your_benchmark --batch_size 1 --log_samples --log_samples_suffix llava_onevision_7b --output_path ./log` can successfully run.



Excuse me, could you tell me where you modified it? Do you know what caused the problem?

**Comment by hulianyuyy** [comment]
I don't know, and the above code works for me.

**Comment by mikeallen39** [comment]
> I don't know, and the above code works for me.



Alright, but thank you very much!
