### ISSUE TITLE
Qwen2.5-Omni-7B CUDA OOM

### ISSUE THREAD

**Issue by yogkul2000** [EvolvingLMMs-Lab/lmms-eval#662]
I was easily able to do SFT on 4 *48GB GPUs, but running evaluation on video benchmarks like video_mmmu or vinoground (very short videos) gives OOM. Only using 1 GPU and splitting the model across the 4 GPUs (device_map="auto"), the issue still persists.

```
Token indices sequence length is longer than the specified maximum sequence length for this model (115108 > 32768). Running this sequence through the model will result in indexing errors
2025-05-03 13:40:54.819 | ERROR    | lmms_eval.models.qwen2_5_omni:generate_until:302 - Error CUDA out of memory. Tried to allocate 334.76 GiB. GPU 0 has a total capacity of 44.42 GiB of which 27.48 GiB is free. Including non-PyTorch memory, this process has 16.93 GiB memory in use. Of the allocated memory 12.10 GiB is allocated by PyTorch, and 4.32 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) in generating
```

**Comment by yogkul2000** [comment]
https://github.com/QwenLM/Qwen2.5-Omni/issues/257#issuecomment-2852311027
I fixed it by installing those specific versions.
